project:
  type: website
  output-dir: docs

website:
  title: "john_letters"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  page-navigation: true    

format:
  html:
    toc: true
    toc-location: left
    theme: superhero
    css: styles.css

listing:
  contents: posts
  sort:
    - "title"
    - "date"

editor: visual